import type { ModelSchema } from "../schema/types.ts";
import { defaultLayout } from "./layout.ts";

/**
 * 课程模型（业务模型，建立在 user/role 之上）：
 * teacherId 指向 school-user（多对一）；registrationSlots 为对象数组（落 JSON 列）。
 */
export const schoolCourseSchema: ModelSchema = {
  type: "object",
  "x-layout": defaultLayout,
  title: "课程列表",
  description: "学校体育课程、授课教师、容量与抢课时段管理。",
  meta: {
    name: "school-course",
    title: "课程列表",
    subtitle: "School Courses",
    description: "学校体育课程、授课教师、容量与抢课时段管理。",
    group: "other",
    singularLabel: "课程",
    pluralLabel: "课程",
    defaultPageSize: 10,
    filterCount: 5,
    openMode: { add: "page", edit: "page", detail: "modal" },
  },
  properties: {
    courseCode: {
      type: "string",
      title: "课程编号",
      component: "Input",
      required: true,
      order: 10,
      props: { placeholder: "请输入课程编号" },
      "x-table": { width: 120 },
      "x-database": { type: "text", unique: true, index: true, filterable: true },
    },
    courseName: {
      type: "string",
      title: "课程名称",
      component: "Input",
      required: true,
      order: 20,
      props: { placeholder: "请输入课程名称" },
      "x-table": { width: 160 },
      "x-database": { type: "text", index: true, filterable: true },
    },
    sportType: {
      type: "string",
      title: "运动项目",
      component: "Select",
      required: true,
      order: 30,
      dataSource: [
        { label: "篮球", value: "basketball" },
        { label: "羽毛球", value: "badminton" },
        { label: "网球", value: "tennis" },
        { label: "足球", value: "football" },
        { label: "乒乓球", value: "table-tennis" },
        { label: "排球", value: "volleyball" },
        { label: "游泳", value: "swimming" },
        { label: "健美操", value: "aerobics" },
      ],
      props: { placeholder: "请选择运动项目" },
      "x-table": { width: 110 },
      "x-database": { type: "text", index: true, filterable: true },
    },
    teacherId: {
      type: "string",
      title: "授课教师",
      component: "Select",
      required: true,
      order: 40,
      props: {
        placeholder: "请选择授课教师",
        service: {
          model: "school-user",
          valueKey: "id",
          labelKey: "displayName",
        },
      },
      "x-table": { width: 130 },
      "x-database": {
        relation: "many-to-one",
        target: "school-user",
        index: true,
        filterable: true,
      },
    },
    semester: {
      type: "string",
      title: "开课学期",
      component: "Select",
      required: true,
      order: 50,
      dataSource: [
        { label: "2026 春季学期", value: "2026-spring" },
        { label: "2026 秋季学期", value: "2026-autumn" },
        { label: "2027 春季学期", value: "2027-spring" },
      ],
      props: { placeholder: "请选择开课学期" },
      "x-table": { width: 140 },
      "x-database": { type: "text", filterable: true },
    },
    gradeScope: {
      title: "适用年级",
      component: "Select",
      required: true,
      order: 60,
      dataSource: [
        { label: "一年级", value: "grade-1" },
        { label: "二年级", value: "grade-2" },
        { label: "三年级", value: "grade-3" },
        { label: "四年级", value: "grade-4" },
        { label: "五年级", value: "grade-5" },
        { label: "六年级", value: "grade-6" },
      ],
      props: { placeholder: "请选择适用年级", selectMode: "multiple" },
      "x-table": { width: 180 },
      "x-database": { type: "json", sortable: false },
    },
    courseDescription: {
      type: "string",
      title: "课程简介",
      component: "Textarea",
      order: 70,
      props: { rows: 3, placeholder: "请输入课程简介" },
      "x-table": { visible: false },
      "x-database": { type: "text" },
    },
    credits: {
      type: "number",
      title: "课程学分",
      component: "NumberInput",
      required: true,
      order: 80,
      props: { placeholder: "请输入课程学分", min: 0, max: 20 },
      "x-table": { width: 100 },
      "x-database": { type: "real", sortable: true },
    },
    maxCapacity: {
      type: "number",
      title: "报名人数上限",
      component: "NumberInput",
      required: true,
      order: 90,
      props: { placeholder: "请输入报名人数上限", min: 1 },
      "x-table": { width: 120 },
      "x-database": { type: "real", sortable: true },
    },
    enrolledCount: {
      type: "number",
      title: "已报名人数",
      component: "NumberInput",
      order: 100,
      default: 0,
      props: { placeholder: "请输入已报名人数", min: 0 },
      "x-table": { width: 110 },
      "x-database": { type: "real", default: 0, sortable: true },
    },
    waitlistEnabled: {
      type: "boolean",
      title: "允许候补报名",
      component: "Select",
      order: 110,
      default: true,
      dataSource: [
        { label: "允许", value: true },
        { label: "不允许", value: false },
      ],
      props: { placeholder: "请选择是否允许候补" },
      "x-table": { width: 110 },
      "x-database": { type: "boolean", default: true, filterable: true },
    },
    waitlistCapacity: {
      type: "number",
      title: "候补人数上限",
      component: "NumberInput",
      order: 120,
      default: 0,
      props: { placeholder: "请输入候补人数上限", min: 0 },
      "x-table": { width: 110 },
      "x-database": { type: "real", default: 0 },
    },
    waitlistCount: {
      type: "number",
      title: "当前候补人数",
      component: "NumberInput",
      order: 130,
      default: 0,
      props: { placeholder: "请输入当前候补人数", min: 0 },
      "x-table": { visible: false },
      "x-database": { type: "real", default: 0 },
    },
    registrationStartAt: {
      type: "string",
      title: "抢课开始时间",
      component: "Input",
      required: true,
      order: 140,
      props: { placeholder: "请输入抢课开始时间，例如 2026-09-01 08:00" },
      "x-table": { width: 160 },
      "x-database": { type: "text" },
    },
    registrationEndAt: {
      type: "string",
      title: "抢课结束时间",
      component: "Input",
      required: true,
      order: 150,
      props: { placeholder: "请输入抢课结束时间，例如 2026-09-07 23:59" },
      "x-table": { width: 160 },
      "x-database": { type: "text" },
    },
    registrationSlots: {
      type: "array",
      component: "ArrayCards",
      order: 155,
      props: { title: "报名抢课时段", gridSpan: 12 },
      "x-table": { width: 260 },
      "x-database": { type: "json" },
      items: {
        type: "object",
        properties: {
          slotName: {
            type: "string",
            title: "时段名称",
            component: "Input",
            required: true,
            order: 10,
            props: { placeholder: "例如：第一轮报名" },
          },
          startAt: {
            type: "string",
            title: "开始时间",
            component: "Input",
            required: true,
            order: 20,
            props: { placeholder: "请输入开始时间，例如 2026-09-01 08:00" },
          },
          endAt: {
            type: "string",
            title: "结束时间",
            component: "Input",
            required: true,
            order: 30,
            props: { placeholder: "请输入结束时间，例如 2026-09-01 12:00" },
          },
          quota: {
            type: "number",
            title: "时段人数上限",
            component: "NumberInput",
            required: true,
            order: 40,
            props: { placeholder: "请输入时段人数上限", min: 1 },
          },
          enrolledCount: {
            type: "number",
            title: "时段已报名人数",
            component: "NumberInput",
            order: 50,
            default: 0,
            props: { placeholder: "请输入时段已报名人数", min: 0 },
          },
          status: {
            type: "string",
            title: "时段状态",
            component: "Select",
            required: true,
            order: 60,
            dataSource: [
              { label: "未开始", value: "pending" },
              { label: "报名中", value: "open" },
              { label: "已结束", value: "closed" },
              { label: "已取消", value: "cancelled" },
            ],
            props: { placeholder: "请选择时段状态" },
          },
        },
      },
    },
    classStartDate: {
      type: "string",
      title: "上课开始日期",
      component: "DateInput",
      order: 160,
      props: { placeholder: "请选择上课开始日期" },
      "x-table": { visible: false },
      "x-database": { type: "text" },
    },
    classEndDate: {
      type: "string",
      title: "上课结束日期",
      component: "DateInput",
      order: 170,
      props: { placeholder: "请选择上课结束日期" },
      "x-table": { visible: false },
      "x-database": { type: "text" },
    },
    weeklySchedule: {
      type: "string",
      title: "每周上课安排",
      component: "Input",
      order: 180,
      props: { placeholder: "例如：周二 16:00-17:30" },
      "x-table": { width: 180 },
      "x-database": { type: "text" },
    },
    location: {
      type: "string",
      title: "上课地点",
      component: "Input",
      order: 190,
      props: { placeholder: "请输入上课地点" },
      "x-table": { width: 140 },
      "x-database": { type: "text" },
    },
    status: {
      type: "string",
      title: "课程状态",
      component: "Select",
      required: true,
      order: 200,
      dataSource: [
        { label: "草稿", value: "draft" },
        { label: "待发布", value: "pending" },
        { label: "报名中", value: "registration" },
        { label: "报名结束", value: "closed" },
        { label: "授课中", value: "running" },
        { label: "已结束", value: "finished" },
        { label: "已停用", value: "disabled" },
      ],
      props: { placeholder: "请选择课程状态" },
      "x-table": { width: 110 },
      "x-database": { type: "text", index: true, filterable: true },
    },
    notes: {
      type: "string",
      title: "备注",
      component: "Textarea",
      order: 210,
      props: { rows: 3, placeholder: "请输入备注" },
      "x-table": { visible: false },
      "x-database": { type: "text" },
    },
    id: { type: "string", title: "ID", display: "none", order: 900, "x-table": { visible: false } },
    createdAt: {
      type: "string",
      title: "创建时间",
      display: "none",
      order: 910,
      "x-table": { visible: false },
    },
    updatedAt: {
      type: "string",
      title: "更新时间",
      display: "none",
      order: 920,
      "x-table": { visible: false },
    },
  },
  group: [
    {
      component: "GridLayout",
      keys: ["courseCode", "courseName", "sportType", "teacherId", "semester", "gradeScope"],
      props: { gridSpan: 12, title: "课程基本信息" },
    },
    {
      component: "GridLayout",
      keys: [
        "credits",
        "maxCapacity",
        "enrolledCount",
        "waitlistEnabled",
        "waitlistCapacity",
        "waitlistCount",
      ],
      props: { gridSpan: 12, title: "报名容量" },
    },
    {
      component: "GridLayout",
      keys: [
        "registrationStartAt",
        "registrationEndAt",
        "classStartDate",
        "classEndDate",
        "weeklySchedule",
        "location",
        "status",
      ],
      props: { gridSpan: 12, title: "时间与上课安排" },
    },
  ],
};
