import type { ModelSchema } from "../schema/types.ts";
import { schoolUserLayout } from "./layout.ts";

/**
 * 用户模型（基础模型，写死）：统一管理教师、学生及其角色归属。
 * roleIds 指向 school-role（多对多，落 junction 表）；
 * homeroomTeacherId 指向 school-user 自身（多对一外键）。
 */
export const schoolUserSchema: ModelSchema = {
  type: "object",
  "x-layout": schoolUserLayout,
  title: "用户管理",
  description: "学校教师、学生及用户角色信息管理。",
  meta: {
    name: "school-user",
    title: "用户管理",
    subtitle: "School Users",
    description: "学校教师、学生及用户角色信息管理。",
    group: "system",
    singularLabel: "用户",
    pluralLabel: "用户",
    defaultPageSize: 10,
    filterCount: 5,
    openMode: { add: "drawer", edit: "page", detail: "modal" },
  },
  properties: {
    userNo: {
      type: "string",
      title: "用户编号",
      component: "Input",
      required: true,
      order: 10,
      props: { placeholder: "请输入用户编号" },
      "x-table": { width: 130 },
      "x-database": { type: "text", unique: true, index: true, filterable: true },
    },
    username: {
      type: "string",
      title: "登录账号",
      component: "Input",
      required: true,
      order: 20,
      props: { placeholder: "请输入登录账号" },
      "x-table": { width: 140 },
      "x-database": { type: "text", unique: true, index: true, filterable: true },
    },
    displayName: {
      type: "string",
      title: "姓名",
      component: "Input",
      required: true,
      order: 30,
      props: { placeholder: "请输入姓名" },
      "x-table": { width: 110 },
      "x-database": { type: "text", index: true, filterable: true },
    },
    userType: {
      type: "string",
      title: "用户类型",
      component: "Select",
      required: true,
      order: 40,
      dataSource: [
        { label: "学生", value: "student" },
        { label: "教师", value: "teacher" },
        { label: "教务管理员", value: "academic-admin" },
        { label: "系统管理员", value: "system-admin" },
      ],
      props: { placeholder: "请选择用户类型" },
      "x-table": { width: 120 },
      "x-database": { type: "text", index: true, filterable: true },
    },
    roleIds: {
      title: "用户角色",
      component: "MultiSelect",
      required: true,
      order: 50,
      props: {
        placeholder: "请选择用户角色",
        service: {
          model: "school-role",
          valueKey: "id",
          labelKey: "roleName",
          remoteSearch: false,
        },
      },
      "x-table": { width: 180 },
      "x-database": { relation: "many-to-many", target: "school-role", sortable: false },
    },
    gender: {
      type: "string",
      title: "性别",
      component: "Select",
      order: 60,
      dataSource: { plugin: "$af-constant", key: "gender" },
      props: { placeholder: "请选择性别" },
      "x-table": { width: 80 },
      "x-database": { type: "text", filterable: true },
    },
    phone: {
      type: "string",
      title: "联系电话",
      component: "Input",
      order: 70,
      props: { placeholder: "请输入联系电话" },
      "x-table": { width: 140 },
      "x-database": { type: "text" },
    },
    email: {
      type: "string",
      title: "邮箱",
      component: "Input",
      order: 80,
      props: { placeholder: "请输入邮箱" },
      "x-table": { width: 180 },
      "x-database": { type: "text" },
    },
    grade: {
      type: "string",
      title: "年级",
      component: "Select",
      order: 90,
      dataSource: { plugin: "$af-constant", key: "grades" },
      props: { placeholder: "请选择年级" },
      "x-table": { width: 100 },
      "x-database": { type: "text", filterable: true },
    },
    deptCode: {
      type: "string",
      title: "所属部门",
      component: "TreeSelect",
      order: 95,
      props: {
        placeholder: "请选择所属部门（学部 / 年级 / 班级 / 党团组织）",
        // 通用组织树来源：从 school-department 按 parentCode 拼树，回填其 deptCode。
        // 换成公司场景只需把 treeModel 指向 company-department，其余不变。
        treeModel: "school-department",
        treeIdField: "deptCode",
        treeLabelField: "deptName",
        treeParentField: "parentCode",
      },
      "x-table": { width: 160 },
      // 标量文本列（非外键）：连接键是部门业务编码 deptCode，须 filterable 才能被
      // 组织树的 deptCode IN [...] 过滤命中（多对多 junction 不可过滤，故不能用成员集反向表达）。
      "x-database": { type: "text", index: true, filterable: true, nullable: true },
    },
    className: {
      type: "string",
      title: "班级",
      component: "Input",
      order: 100,
      props: { placeholder: "请输入班级" },
      "x-table": { width: 120 },
      "x-database": { type: "text" },
    },
    studentNo: {
      type: "string",
      title: "学号",
      component: "Input",
      order: 110,
      props: { placeholder: "请输入学号" },
      "x-table": { width: 130 },
      "x-database": { type: "text" },
    },
    department: {
      type: "string",
      title: "所属院系/部门",
      component: "Input",
      order: 120,
      props: { placeholder: "请输入所属院系或部门" },
      "x-table": { width: 150 },
      "x-database": { type: "text" },
    },
    teacherTitle: {
      type: "string",
      title: "教师职称",
      component: "Select",
      order: 130,
      dataSource: [
        { label: "助教", value: "assistant" },
        { label: "讲师", value: "lecturer" },
        { label: "副教授", value: "associate-professor" },
        { label: "教授", value: "professor" },
      ],
      props: { placeholder: "请选择教师职称" },
      "x-table": { width: 120 },
      "x-database": { type: "text" },
    },
    homeroomTeacherId: {
      type: "string",
      title: "班主任",
      component: "Select",
      order: 140,
      props: {
        placeholder: "请选择班主任",
        service: {
          model: "school-user",
          valueKey: "id",
          labelKey: "displayName",
          remoteSearch: false,
        },
      },
      "x-table": { width: 110 },
      "x-database": { relation: "many-to-one", target: "school-user" },
    },
    status: {
      type: "string",
      title: "账号状态",
      component: "Select",
      required: true,
      order: 150,
      dataSource: [
        { label: "正常", value: "active" },
        { label: "未激活", value: "pending" },
        { label: "已禁用", value: "disabled" },
        { label: "已注销", value: "closed" },
      ],
      props: { placeholder: "请选择账号状态" },
      "x-table": { width: 100 },
      "x-database": {
        type: "text",
        nullable: false,
        default: "active",
        index: true,
        filterable: true,
      },
    },
    passwordHash: {
      type: "string",
      title: "密码哈希",
      component: "Input",
      display: "none",
      order: 155,
      "x-table": { visible: false },
      "x-database": { type: "text" },
    },
    openid: {
      type: "string",
      title: "微信 OpenID",
      component: "Input",
      display: "none",
      order: 156,
      "x-table": { visible: false },
      "x-database": { type: "text", index: true, filterable: true },
    },
    lastLoginAt: {
      type: "string",
      title: "最后登录时间",
      component: "DateInput",
      order: 160,
      props: { placeholder: "请选择最后登录时间" },
      "x-table": { visible: false },
      "x-database": { type: "text" },
    },
    remark: {
      type: "string",
      title: "备注",
      component: "Textarea",
      order: 170,
      props: { rows: 3, placeholder: "请输入备注" },
      "x-table": { visible: false },
      "x-database": { type: "text" },
    },
    id: { type: "string", title: "ID", display: "none", order: 900, "x-table": { visible: false } },
    createdAt: {
      type: "string",
      title: "创建时间",
      display: "none",
      order: 910,
      "x-table": { visible: false },
    },
    updatedAt: {
      type: "string",
      title: "更新时间",
      display: "none",
      order: 920,
      "x-table": { visible: false },
    },
  },
  group: [
    {
      component: "GridLayout",
      keys: ["userNo", "username", "displayName", "userType", "roleIds", "status"],
      props: { gridSpan: 12, title: "账号信息" },
    },
    {
      component: "GridLayout",
      keys: [
        "gender",
        "phone",
        "email",
        "grade",
        "deptCode",
        "className",
        "studentNo",
        "department",
        "teacherTitle",
        "homeroomTeacherId",
      ],
      props: { gridSpan: 12, title: "人员信息" },
    },
  ],
};
