import type { ModelSchema } from "../schema/types.ts";
import { defaultLayout } from "./layout.ts";
import { defaultFields } from "./_defaults.ts";

/**
 * 角色模型（权限基础模型，写死）：维护角色及其可查看的数据表。
 * viewableTables 即最朴素的「权限存储」——记录该角色能看哪些模型。
 */
export const schoolRoleSchema: ModelSchema = {
  type: "object",
  "x-layout": defaultLayout,
  title: "角色管理",
  description: "学校用户角色与可查看业务表配置。",
  meta: {
    name: "school-role",
    title: "角色管理",
    subtitle: "School Roles",
    description: "学校用户角色与可查看业务表配置。",
    group: "system",
    singularLabel: "角色",
    pluralLabel: "角色",
    defaultPageSize: 10,
    filterCount: 3,
    openMode: { add: "modal", edit: "modal", detail: "modal" },
  },
  properties: {
    roleCode: {
      type: "string",
      title: "角色编码",
      component: "Input",
      required: true,
      order: 10,
      props: { placeholder: "请输入角色编码" },
      "x-table": { width: 150 },
      "x-database": { type: "text", unique: true, index: true, filterable: true },
    },
    roleName: {
      type: "string",
      title: "角色名称",
      component: "Input",
      required: true,
      order: 20,
      props: { placeholder: "请输入角色名称" },
      "x-table": { width: 140 },
      "x-database": { type: "text", index: true, filterable: true },
    },
    roleType: {
      type: "string",
      title: "角色类型",
      component: "Select",
      required: true,
      order: 30,
      dataSource: [
        { label: "学生", value: "student" },
        { label: "课程老师", value: "course-teacher" },
        { label: "班主任", value: "homeroom-teacher" },
        { label: "年级主任", value: "grade-director" },
        { label: "校级领导", value: "school-leader" },
        { label: "教务管理员", value: "academic-admin" },
      ],
      props: { placeholder: "请选择角色类型" },
      "x-table": { width: 130 },
      "x-database": { type: "text", index: true, filterable: true },
    },
    roleLevel: {
      type: "string",
      title: "管理层级",
      component: "Select",
      required: true,
      order: 40,
      dataSource: [
        { label: "个人", value: "self" },
        { label: "班级", value: "class" },
        { label: "年级", value: "grade" },
        { label: "全校", value: "school" },
      ],
      props: { placeholder: "请选择管理层级" },
      "x-table": { width: 100 },
      "x-database": { type: "text", filterable: true },
    },
    viewableTables: {
      title: "可查看数据表",
      component: "Select",
      required: true,
      order: 50,
      dataSource: [
        { label: "课程列表", value: "school-course" },
        { label: "用户管理", value: "school-user" },
        { label: "角色管理", value: "school-role" },
      ],
      props: { placeholder: "请选择可查看数据表", selectMode: "multiple" },
      "x-table": { width: 220 },
      "x-database": { type: "json", sortable: false },
    },
    description: {
      type: "string",
      title: "角色说明",
      component: "Textarea",
      order: 60,
      props: { rows: 3, placeholder: "请输入角色说明" },
      "x-table": { visible: false },
      "x-database": { type: "text" },
    },
    enabled: {
      type: "boolean",
      title: "是否启用",
      component: "Select",
      order: 70,
      default: true,
      dataSource: [
        { label: "启用", value: true },
        { label: "停用", value: false },
      ],
      props: { placeholder: "请选择状态" },
      "x-table": { width: 100 },
      "x-database": { type: "boolean", default: true, filterable: true },
    },
    sortOrder: {
      type: "number",
      title: "排序号",
      component: "NumberInput",
      order: 80,
      default: 0,
      props: { placeholder: "请输入排序号", min: 0 },
      "x-table": { width: 90 },
      "x-database": { type: "real", default: 0, sortable: true },
    },
    ...defaultFields(),
  },
  group: [
    {
      component: "GridLayout",
      keys: ["roleCode", "roleName", "roleType", "roleLevel", "enabled", "sortOrder"],
      props: { gridSpan: 12, title: "角色信息" },
    },
    {
      component: "GridLayout",
      keys: ["viewableTables", "description"],
      props: { gridSpan: 12, title: "数据查看范围" },
    },
  ],
};
