import type { ModelRecord } from "../../types/record";

function isoDaysAgo(daysAgo: number, hour: number, minute: number) {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  date.setHours(hour, minute, 0, 0);
  return date.getTime();
}

function withUpdatedAt(createdAt: number, minutesLater: number) {
  const date = new Date(createdAt);
  date.setMinutes(date.getMinutes() + minutesLater);
  return date.getTime();
}

export function createDemoRecords(): Record<string, ModelRecord[]> {
  const employees: ModelRecord[] = [
    {
      id: "employee-1",
      employeeName: "Luna",
      age: 28,
      level: "senior",
      hourlyRate: 260,
      hiredAt: "2025-01-10",
      serviceIds: ["service-1", "service-3", "service-4"],
      serviceSlots: ["10:00", "11:00", "14:00", "15:00", "18:00"],
      editablePermissions: [
        { record: "nail-booking", fieldKeys: ["status", "preferenceNotes", "depositPaid"] },
        { record: "nail-service", fieldKeys: ["price", "styleDescription"] },
      ],
      skills: ["延长建构", "节日手绘", "高客单"],
      active: true,
      notes: "负责高客单预约和复杂款式复购客户。",
      createdAt: isoDaysAgo(20, 10, 0),
      updatedAt: withUpdatedAt(isoDaysAgo(20, 10, 0), 35),
    },
    {
      id: "employee-2",
      employeeName: "Momo",
      age: 24,
      level: "middle",
      hourlyRate: 190,
      hiredAt: "2025-03-08",
      serviceIds: ["service-1", "service-2"],
      serviceSlots: ["08:00", "09:00", "12:00", "13:00", "16:00", "17:00"],
      editablePermissions: [
        { record: "nail-booking", fieldKeys: ["bookingDate", "serviceSlot", "preferenceNotes"] },
      ],
      skills: ["猫眼渐变", "纯色快单", "手部护理"],
      active: true,
      notes: "擅长午间快单和工作日高频预约。",
      createdAt: isoDaysAgo(18, 10, 0),
      updatedAt: withUpdatedAt(isoDaysAgo(18, 10, 0), 42),
    },
    {
      id: "employee-3",
      employeeName: "Kiki",
      age: 31,
      level: "senior",
      hourlyRate: 280,
      hiredAt: "2024-12-16",
      serviceIds: ["service-2", "service-3", "service-4"],
      serviceSlots: ["09:00", "10:00", "13:00", "16:00", "19:00", "20:00"],
      editablePermissions: [
        { record: "nail-employee", fieldKeys: ["serviceSlots", "serviceIds"] },
        { record: "nail-booking", fieldKeys: ["status", "serviceSlot"] },
      ],
      skills: ["法式延长", "婚礼定制", "低饱和设计"],
      active: true,
      notes: "主要承接婚礼档期和节假日定制预约。",
      createdAt: isoDaysAgo(16, 10, 0),
      updatedAt: withUpdatedAt(isoDaysAgo(16, 10, 0), 50),
    },
    {
      id: "employee-4",
      employeeName: "Nora",
      age: 22,
      level: "junior",
      hourlyRate: 150,
      hiredAt: "2025-04-20",
      serviceIds: ["service-1"],
      serviceSlots: ["08:00", "11:00", "12:00", "15:00", "17:00"],
      editablePermissions: [
        { record: "nail-booking", fieldKeys: ["bookingDate", "serviceId"] },
      ],
      skills: ["基础护理", "卸甲修型", "手部保养"],
      active: true,
      notes: "负责基础护理和新客体验单。",
      createdAt: isoDaysAgo(14, 10, 0),
      updatedAt: withUpdatedAt(isoDaysAgo(14, 10, 0), 58),
    },
  ];

  const services: ModelRecord[] = [
    {
      id: "service-1",
      serviceName: "日常纯色护理",
      category: "care",
      durationMinutes: 60,
      price: 168,
      difficulty: "standard",
      styleDescription: "以纯色和基础修型为主，适合日常通勤和短时段预约。",
      styleTags: ["通勤", "显手白", "高复购"],
      employeeIds: ["employee-1", "employee-2", "employee-4"],
      scenes: ["工作日快单", "新客体验"],
      notes: "支持加购卸甲和基础手护。",
      createdAt: isoDaysAgo(12, 11, 20),
      updatedAt: withUpdatedAt(isoDaysAgo(12, 11, 20), 20),
    },
    {
      id: "service-2",
      serviceName: "猫眼渐变设计",
      category: "design",
      durationMinutes: 90,
      price: 238,
      difficulty: "advanced",
      styleDescription: "猫眼、跳色和低饱和渐变结合，适合社交聚会和轻设计需求。",
      styleTags: ["猫眼", "低饱和", "拍照好看"],
      employeeIds: ["employee-2", "employee-3"],
      scenes: ["约会", "聚会"],
      notes: "建议提前确认主色和跳色组合。",
      createdAt: isoDaysAgo(11, 11, 20),
      updatedAt: withUpdatedAt(isoDaysAgo(11, 11, 20), 33),
    },
    {
      id: "service-3",
      serviceName: "法式延长套餐",
      category: "extension",
      durationMinutes: 120,
      price: 328,
      difficulty: "advanced",
      styleDescription: "提供法式延长和基础建构，适合长甲和宴会型造型需求。",
      styleTags: ["法式", "长甲", "建构"],
      employeeIds: ["employee-1", "employee-3"],
      scenes: ["宴会", "写真"],
      notes: "到店前需确认手型和延长长度偏好。",
      createdAt: isoDaysAgo(10, 11, 20),
      updatedAt: withUpdatedAt(isoDaysAgo(10, 11, 20), 41),
    },
    {
      id: "service-4",
      serviceName: "节日定制礼盒款",
      category: "festival",
      durationMinutes: 150,
      price: 428,
      difficulty: "custom",
      styleDescription: "结合节庆主题、手绘和立体装饰的高定款式，适合强主题预约。",
      styleTags: ["节日", "高定", "手绘"],
      employeeIds: ["employee-1", "employee-3"],
      scenes: ["节假日", "婚礼"],
      notes: "建议至少提前两天锁定档期和设计图。",
      createdAt: isoDaysAgo(9, 11, 20),
      updatedAt: withUpdatedAt(isoDaysAgo(9, 11, 20), 52),
    },
  ];

  const bookings: ModelRecord[] = [
    {
      id: "nail-booking-1",
      customerName: "林晚",
      phone: "1380000200",
      serviceId: "service-1",
      employeeId: "employee-2",
      bookingDate: "2026-06-04",
      serviceSlot: "12:00",
      status: "draft",
      depositPaid: false,
      styleTags: ["通勤", "裸粉", "短甲"],
      preferenceNotes: "希望一个小时内完成，优先选显手白纯色。",
      createdAt: isoDaysAgo(8, 12, 15),
      updatedAt: withUpdatedAt(isoDaysAgo(8, 12, 15), 15),
    },
    {
      id: "nail-booking-2",
      customerName: "周周",
      phone: "1380000201",
      serviceId: "service-2",
      employeeId: "employee-3",
      bookingDate: "2026-06-05",
      serviceSlot: "13:00",
      status: "review",
      depositPaid: true,
      styleTags: ["猫眼", "低饱和", "约会"],
      preferenceNotes: "已发参考图，想保留一点跳色层次。",
      createdAt: isoDaysAgo(7, 13, 15),
      updatedAt: withUpdatedAt(isoDaysAgo(7, 13, 15), 19),
    },
    {
      id: "nail-booking-3",
      customerName: "陈雨",
      phone: "1380000202",
      serviceId: "service-3",
      employeeId: "employee-1",
      bookingDate: "2026-06-06",
      serviceSlot: "14:00",
      status: "published",
      depositPaid: true,
      styleTags: ["法式", "延长", "宴会"],
      preferenceNotes: "周末参加宴会，需要偏成熟的法式延长款。",
      createdAt: isoDaysAgo(6, 14, 15),
      updatedAt: withUpdatedAt(isoDaysAgo(6, 14, 15), 23),
    },
    {
      id: "nail-booking-4",
      customerName: "Mia",
      phone: "1380000203",
      serviceId: "service-4",
      employeeId: "employee-3",
      bookingDate: "2026-06-07",
      serviceSlot: "19:00",
      status: "archived",
      depositPaid: true,
      styleTags: ["节日", "手绘", "闪片"],
      preferenceNotes: "上次做的是圣诞礼盒款，这次想换成生日主题。",
      createdAt: isoDaysAgo(5, 15, 15),
      updatedAt: withUpdatedAt(isoDaysAgo(5, 15, 15), 31),
    },
    {
      id: "nail-booking-5",
      customerName: "阿宁",
      phone: "1380000204",
      serviceId: "service-2",
      employeeId: "employee-2",
      bookingDate: "2026-06-08",
      serviceSlot: "16:00",
      status: "draft",
      depositPaid: false,
      styleTags: ["猫眼", "工作日", "显白"],
      preferenceNotes: "希望下班前完成，颜色尽量低调但有层次。",
      createdAt: isoDaysAgo(4, 16, 15),
      updatedAt: withUpdatedAt(isoDaysAgo(4, 16, 15), 27),
    },
    {
      id: "nail-booking-6",
      customerName: "Yoyo",
      phone: "1380000205",
      serviceId: "service-3",
      employeeId: "employee-3",
      bookingDate: "2026-06-09",
      serviceSlot: "20:00",
      status: "review",
      depositPaid: true,
      styleTags: ["长甲", "写真", "法式"],
      preferenceNotes: "要配合写真拍摄，需要偏冷调法式线条。",
      createdAt: isoDaysAgo(3, 17, 15),
      updatedAt: withUpdatedAt(isoDaysAgo(3, 17, 15), 25),
    },
    {
      id: "nail-booking-7",
      customerName: "苏苏",
      phone: "1380000206",
      serviceId: "service-4",
      employeeId: "employee-1",
      bookingDate: "2026-06-10",
      serviceSlot: "18:00",
      status: "published",
      depositPaid: true,
      styleTags: ["高定", "婚礼", "珍珠"],
      preferenceNotes: "婚礼试妆同步预约，希望先看两版主题方案。",
      createdAt: isoDaysAgo(2, 18, 15),
      updatedAt: withUpdatedAt(isoDaysAgo(2, 18, 15), 29),
    },
    {
      id: "nail-booking-8",
      customerName: "Kiki",
      phone: "1380000207",
      serviceId: "service-1",
      employeeId: "employee-4",
      bookingDate: "2026-06-11",
      serviceSlot: "11:00",
      status: "review",
      depositPaid: false,
      styleTags: ["基础护理", "修型"],
      preferenceNotes: "新客首次到店，先做基础护理和卸甲修型。",
      createdAt: isoDaysAgo(1, 19, 15),
      updatedAt: withUpdatedAt(isoDaysAgo(1, 19, 15), 17),
    },
  ];

  return {
    "nail-employee": employees,
    "nail-service": services,
    "nail-booking": bookings,
  };
}
