import type { IFormSchema } from "@alien-form/react";

export const goodsFormSchema: IFormSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      title: "商品名称",
      component: "Input",
      decorator: "FormItem",
      required: true,
      validate: { minLength: 2, maxLength: 100 },
      props: { placeholder: "请输入商品名称" },
      order: 10,
    },
    category: {
      type: "string",
      title: "商品分类",
      component: "Select",
      decorator: "FormItem",
      required: true,
      dataSource: [
        { label: "数码电子", value: "electronics" },
        { label: "服饰鞋包", value: "clothing" },
        { label: "家居生活", value: "home" },
        { label: "食品饮料", value: "food" },
        { label: "美妆个护", value: "beauty" },
      ],
      props: { placeholder: "请选择分类" },
      order: 20,
    },
    price: {
      type: "number",
      title: "售价（元）",
      component: "NumberInput",
      decorator: "FormItem",
      required: true,
      validate: { minimum: 0.01, message: "售价必须大于 0" },
      props: { placeholder: "请输入售价", min: 0 },
      order: 30,
    },
    stock: {
      type: "number",
      title: "库存",
      component: "NumberInput",
      decorator: "FormItem",
      required: true,
      validate: { minimum: 0, message: "库存不能为负" },
      props: { placeholder: "请输入库存数量", min: 0 },
      order: 40,
    },
    status: {
      type: "string",
      title: "状态",
      component: "Select",
      decorator: "FormItem",
      required: true,
      dataSource: [
        { label: "生效中", value: "active" },
        { label: "审核中", value: "reviewing" },
        { label: "草稿", value: "draft" },
        { label: "已下架", value: "offline" },
      ],
      default: "draft",
      props: { placeholder: "请选择状态" },
      order: 50,
    },
    cover: {
      type: "string",
      title: "封面图",
      component: "Input",
      decorator: "FormItem",
      props: { placeholder: "请输入图片 URL" },
      order: 60,
    },
    description: {
      type: "string",
      title: "商品描述",
      component: "Textarea",
      decorator: "FormItem",
      props: { placeholder: "请输入商品描述", rows: 4 },
      order: 70,
    },
    specs: {
      type: "array",
      title: "规格参数",
      description: "添加商品的规格属性",
      component: "ArrayCards",
      decorator: "FormItem",
      props: { addText: "+ 添加规格" },
      order: 80,
      items: {
        type: "object",
        properties: {
          name: {
            type: "string",
            title: "规格名",
            component: "Input",
            decorator: "FormItem",
            required: true,
            props: { placeholder: "如：颜色、尺寸" },
            order: 10,
          },
          value: {
            type: "string",
            title: "规格值",
            component: "Input",
            decorator: "FormItem",
            required: true,
            props: { placeholder: "如：黑色、XL" },
            order: 20,
          },
        },
      },
    },
  },
};
